#! /bin/sh

DIR=`dirname $0`

JS="d8 $DIR/../utility/debug.js $DIR/../utility/system.js $DIR/../utility/hashmap.js $DIR/misc.js $DIR/scanner.js $DIR/parser.js $DIR/pp.js $DIR/ast-passes.js $DIR/js.js --"

# After a "make boostrap" this can be used instead:
#
#JS="$DIR/js.js.exe"

$JS "$@"
