d8                                  \
    utility/debug.js                \
    utility/system.js               \
    utility/iterators.js            \
    utility/graph.js                \
    utility/arrays.js               \
    utility/hashmap.js              \
    utility/linkedlist.js           \
    utility/strings.js              \
    utility/modules.js              \
    utility/misc.js                 \
    utility/xml.js                  \
    utility/html.js                 \
    parser/misc.js                  \
    parser/scanner.js               \
    parser/parser.js                \
    parser/pp.js                    \
    parser/ast-passes.js            \
    platform/memory.js              \
    ir/static.js                    \
    ir/instructions.js              \
    ir/iir.js                       \
    ir/cfg.js                       \
    ir/functions.js                 \
    ir/ir.js                        \
    ir/optpatterns.js               \
    ir/constprop.js                 \
    ir/commelim.js                  \
    ir/inlining.js                  \
    ir/lowering.js                  \
    frontend.js                     \
    runtime/objlayout.js            \
    runtime/context.js              \
    runtime/objects.js              \
    codegen/asm.js                  \
    codegen/asm-x86.js              \
    codegen/linearscan.js           \
    codegen/backend.js              \
    codegen/ir-to-asm-x86.js        \
    codegen/regalloc-config-x86.js  \
    jslib/errors.js                 \
    compiler.js                     \
    init.js                         \
                                    \
    bench/platforms.js              \
    bench/dimensions.js             \
    bench/benchmarks.js             \
    bench/benchmarking.js           \
    bench/reports.js                \
    bench/benchmain.js              \
                                    \
    --allow_natives_syntax -- $*
